# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c64337b1e2b47907604a7efbd78e0932c21334df42c445a0d08505619252800dc379b92740e82a331c15c9db144e2f0e04d503c3342a6f7558a8019ed43478

test:
  secret_key_base: a47b8cb5d8711d62cc68ed789e1ebc32ffcf1be77c088e758c237e52be6af43052f7811957d5c7bfaf23dcfd98605592ee25c4261b448464426a93fbca7e8df5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
